version: '3'

services:
  vue:
    build:
      context: ./docker/vue
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/frontend
    tty: true
    working_dir: /frontend
    command: ash -c 'yarn && yarn serve'

  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./frontend/dist:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /app